# Generated by Django 2.1.7 on 2019-04-08 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='status',
            field=models.IntegerField(choices=[(0, 'Survey'), (1, 'Anggota Baru')]),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
