# Generated by Django 2.1.7 on 2019-04-08 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penagihan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penagihan',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
